spring.application.name=MEDICAL-SERVICE
server.port=8083

spring.mongodb.uri=mongodb://mongodb:27017/medical_db

# Kafka - connexion au conteneur Docker
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=medical-group
spring.kafka.consumer.auto-offset-reset=earliest

