spring.application.name=SCAN-SERVICE
server.port=8084

spring.mongodb.uri=mongodb://mongodb:27017/scan_db

# Kafka - connexion au conteneur Docker
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=scan-group
spring.kafka.consumer.auto-offset-reset=earliest

